---

- name: Install AmneziaWG dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
      - python3-launchpadlib
      - gnupg2
      - "linux-headers-{{ ansible_kernel }}"
    state: present
    update_cache: true

- name: Add AmneziaWG repository
  ansible.builtin.apt_repository:
    repo: ppa:amnezia/ppa
    state: present
    update_cache: true

- name: install AWG
  ansible.builtin.apt:
    name: amneziawg
    state: present
    update_cache: true

- name: Check AWG
  ansible.builtin.command:
    cmd: modinfo amneziawg
  changed_when: false