[vps]
ndrl ansible_host=109.107.175.116
ltv ansible_host=193.233.83.45

[vps:vars]
ansible_user=evg
ansible_ssh_private_key_file=~/.ssh/iac_lab

[gateway]
lb01

[kafka]
kafka01
kafka02
kafka03

[kafka:vars]
ansible_user=evg
ansible_ssh_private_key_file=~/.ssh/iac_lab
ansible_ssh_common_args='-o ProxyJump=lb01'


[ipsec_gateways]
lb01
ndrl ansible_user=evg