---

- name: Configure kafka cluster
  hosts: kafka
  become: true

  tasks:
    - name: Install Java 21
      ansible.builtin.apt:
        name: openjdk-21-jre-headless
        state: present
        update_cache: true

    - name: Download Kafka archive to Ansible host
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/kafka/3.9.2/kafka_2.13-3.9.2.tgz
        dest: "{{ playbook_dir }}/../artifacts/kafka_2.13-3.9.2.tgz"
        mode: "0644"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Copy Kafka archive to Kafka nodes
      ansible.builtin.copy:
        src: /tmp/kafka_2.13-3.9.2.tgz
        dest: /tmp/kafka_2.13-3.9.2.tgz
        mode: "0644"

    - name: Create kafka system user
      ansible.builtin.user:
        name: kafka
        system: true
        shell: /usr/sbin/nologin
        create_home: false

    - name: Extract Kafka
      ansible.builtin.unarchive:
        src: /tmp/kafka_2.13-3.9.2.tgz
        dest: /opt
        remote_src: true
        creates: /opt/kafka_2.13-3.9.2

    - name: Create kafka symlink
      ansible.builtin.file:
        src: /opt/kafka_2.13-3.9.2
        dest: /opt/kafka
        state: link

    - name: Set Kafka directory owner
      ansible.builtin.file:
        path: /opt/kafka_2.13-3.9.2
        owner: kafka
        group: kafka
        recurse: true